from __future__ import annotations

from typing import Any, Dict, List

from .library_expansion import EXTRA_PLAYS


# PLAY LIBRARY
# Each entry includes coaching reads: vs_man, vs_zone, kill_look, vulnerabilities,
# post_snap_alert, and optionally td_pct (red zone).
#
# Optional metadata (see ``playcaller.play_metadata``): featured_roles, situation
# fits (red_zone_fit, short_yardage_fit, …), blitz_answer, explosive_potential,
# risk_level, man_beater, zone_beater, fourth_down_fit, clock_safe, goal_line_fit.
# Omitted keys use family/name/global defaults so older plays keep working.

PLAY_LIBRARY: Dict[str, List[Dict[str, Any]]] = {
    # ── QUICK GAME ────────────────────────────────────────────────────────────
    "quick_game": [
        {
            "name": "Stick",
            "personnel": "11",
            "formation": "Shotgun Trips Right",
            "protection": "6-man half-slide protection",
            "routes": {
                "X": "Backside slant",
                "H": "Stick route",
                "Y": "Flat / arrow",
                "Z": "Outside clear fade",
                "RB": "Check-release weak",
            },
            "vs_man": "H should win the stick vs. press — attack the flat combo immediately.",
            "vs_zone": "H settles in the hole between LB and flat defender; Y stretches the flat.",
            "kill_look": "Cover 0 / zero blitz with bracket on the outside — check to RB hot.",
            "vulnerabilities": ["cover_0", "zero_blitz", "inside_bracket"],
            "post_snap_alert": "If single safety rotates high post-snap, Z fade is live on the back shoulder.",
            "why": "High-percentage concept that attacks underneath leverage and gets the ball out quickly.",
        },
        {
            "name": "Spacing",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "protection": "5-man scat protection",
            "routes": {
                "X": "Hitch",
                "H": "Hook",
                "Y": "Hook",
                "Z": "Hitch",
                "RB": "Middle settle / checkdown",
            },
            "vs_man": "Hitches beat off-coverage; X and Z need clean outside releases.",
            "vs_zone": "Hooks find voids; RB middle settle is the safety valve.",
            "kill_look": "Press-man with corner blitz — hitches will be covered tight; hot to RB.",
            "vulnerabilities": ["press_man", "corner_blitz", "cover_0"],
            "post_snap_alert": "If ILB drops to hook-curl zone, RB middle settle is immediate.",
            "why": "Good versus zone; safe completion around the sticks.",
        },
        {
            "name": "Slant-Flat",
            "personnel": "11",
            "formation": "Shotgun Trips Left",
            "protection": "6-man slide protection",
            "routes": {
                "X": "Boundary slant",
                "H": "Flat",
                "Y": "Seam clear",
                "Z": "Backside dig sit",
                "RB": "Check-release strong",
            },
            "vs_man": "X slant beats inside leverage immediately; flat is the quick answer vs. press.",
            "vs_zone": "H flat pulls CB and opens X slant window; Z dig sits in vacated zone.",
            "kill_look": "Cloud coverage on the trips side (CB over flat, safety over top) — work backside Z.",
            "vulnerabilities": ["cloud_coverage", "cover_3_buzz", "two_high_bracket"],
            "post_snap_alert": "If MIKE scrapes hard to the flat, Z backside dig sit is wide open.",
            "why": "Simple read with a clean triangle on the front side.",
        },
    ],
    # ── DROPBACK PASS ─────────────────────────────────────────────────────────
    "dropback_pass": [
        {
            "name": "Dagger",
            "personnel": "11",
            "formation": "Shotgun Trips Right",
            "protection": "6-man half-slide with RB scan",
            "routes": {
                "X": "Backside hitch",
                "H": "Clear vertical seam",
                "Y": "12-15 yard dig",
                "Z": "Outside go / clear",
                "RB": "Check-release",
            },
            "vs_man": "H clears the safety; Y dig is the primary read vs. man after the clear.",
            "vs_zone": "H seam stresses the deep third; Y digs into the vacated MOF window.",
            "kill_look": "Cover 0 / all-out blitz — get to quick game or screen immediately.",
            "vulnerabilities": ["cover_0", "all_out_blitz", "zero_coverage"],
            "post_snap_alert": "If safety jumps H seam early, Y dig window opens — throw it.",
            "why": "Strong medium-to-long yardage concept; stresses safeties and opens the dig.",
        },
        {
            "name": "Drive",
            "personnel": "11",
            "formation": "Gun Doubles",
            "protection": "6-man protection",
            "routes": {
                "X": "Dig",
                "H": "Shallow cross",
                "Y": "Sit over ball",
                "Z": "Clear post",
                "RB": "Swing / outlet",
            },
            "vs_man": "H shallow cross is hot vs. man; X dig beats trail technique.",
            "vs_zone": "H clears underneath defenders; Y settles in the void behind them.",
            "kill_look": "MIKE walks up to the line with no weak-side LB depth — check to draw or screen.",
            "vulnerabilities": ["cover_0", "fire_zone_3", "MIKE_blitz"],
            "post_snap_alert": "If Z clears two safeties, X dig is working single coverage.",
            "why": "Reliable chain-mover against both man and zone.",
        },
        {
            "name": "Y-Cross",
            "personnel": "11",
            "formation": "Shotgun Trips Open",
            "protection": "7-man protection",
            "routes": {
                "X": "Backside comeback",
                "H": "Over / cross",
                "Y": "Deep cross",
                "Z": "Clear go",
                "RB": "Strong insert then check-release",
            },
            "vs_man": "Y deep cross is a winner vs. man; Z clears the safety off the field.",
            "vs_zone": "H and Y create layered stress across the field; attack the second level.",
            "kill_look": "Tampa 2 — MIKE will drop to the deep middle and bracket Y; work H underneath.",
            "vulnerabilities": ["tampa_2", "cover_4_bracket", "robber_coverage"],
            "post_snap_alert": "If safety rotates to Z side, X comeback backside is single coverage.",
            "why": "Creates layered cross-field stress; use when you need more than a quick throw.",
        },
    ],
    # ── SCREEN ────────────────────────────────────────────────────────────────
    "screen": [
        {
            "name": "RB Middle Screen",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "protection": "Invite the rush; OL delayed release",
            "routes": {
                "X": "Clear outside",
                "H": "Mandatory outside release",
                "Y": "Clear seam",
                "Z": "Clear vertical",
                "RB": "Middle screen",
            },
            "vs_man": "Man coverage chases receivers downfield — clear path for the screen.",
            "vs_zone": "Works if LBs are rushing; zone defenders dropping may read the screen.",
            "kill_look": "Linebackers sitting in coverage with minimal rush — they will see this develop.",
            "vulnerabilities": ["spy_linebacker", "3_man_rush", "zone_drop"],
            "post_snap_alert": "If LBs drop to zones at the snap, check out at the line if possible.",
            "why": "Good answer to long-yardage pressure looks.",
        },
        {
            "name": "Trips Bubble",
            "personnel": "11",
            "formation": "Trips Right",
            "protection": "Quick perimeter action",
            "routes": {
                "X": "Backside glance",
                "H": "Bubble",
                "Y": "Block alley / stalk",
                "Z": "Block corner / stalk",
                "RB": "Inside check",
            },
            "vs_man": "Numbers game on the perimeter — should have a blocker advantage.",
            "vs_zone": "Works if the overhang is aggressive; check MOFO safety alignment pre-snap.",
            "kill_look": "Extra defender walked out over trips — they've matched numbers; check inside.",
            "vulnerabilities": ["pattern_match_cover_4", "extra_overhang", "trips_adjustment"],
            "post_snap_alert": "Count defenders on the perimeter pre-snap — if 3-on-3, look inside first.",
            "why": "Simple space play if numbers are favorable.",
        },
    ],
    # ── PLAY ACTION ───────────────────────────────────────────────────────────
    "play_action": [
        {
            "name": "Boot Flood",
            "personnel": "12",
            "formation": "Singleback Twins",
            "protection": "Wide zone play-action boot protection",
            "routes": {
                "X": "Backside post / crosser clear",
                "Y": "Deep out",
                "H": "Flat in boot path",
                "Z": "Intermediate over",
                "RB": "Run fake then edge seal",
            },
            "vs_man": "H flat in boot path should be open immediately vs. man rotating to run.",
            "vs_zone": "Y deep out and H flat create a high-low on the perimeter defender.",
            "kill_look": "Defense in pure pass look — they won't bite on the fake; PA loses its effect.",
            "vulnerabilities": ["cover_4", "quarters_pattern_match", "no_run_fill_defense"],
            "post_snap_alert": "If the corner sits flat, Y deep out is live — take the shot.",
            "why": "Changes launch point and creates a clean high-low on the perimeter.",
        },
        {
            "name": "Y-Leak",
            "personnel": "12",
            "formation": "Singleback Ace",
            "protection": "Max protect play-action",
            "routes": {
                "X": "Post clear",
                "Y": "Delayed leak",
                "H": "Deep crosser",
                "Z": "Comeback",
                "RB": "Run fake / insert protect",
            },
            "vs_man": "Y leak beats any linebacker in man coverage — automatic matchup win.",
            "vs_zone": "Y leaks into the seam as H clears the intermediate level.",
            "kill_look": "Two-high with LBs in hook-curl — Y leak will be bracketed; take H crosser.",
            "vulnerabilities": ["two_high_match", "cover_2_bracket", "linebacker_spy"],
            "post_snap_alert": "If strong safety attacks the Y fake, H deep crosser is one-on-one.",
            "why": "Red-zone shot-play when the defense overreacts to run action.",
            "td_pct": 0.51,
        },
    ],
    # ── RUN GAME ──────────────────────────────────────────────────────────────
    "inside_zone": [
        {
            "name": "Inside Zone Strong",
            "personnel": "11",
            "formation": "Shotgun Trips Right",
            "run_scheme": "Inside zone to the strength",
            "blocking": "Covered/uncovered zone rules; RB presses front-side A/B gap",
            "vs_man": "Key the double at the point of attack; MIKE movement sets the cut.",
            "vs_zone": "Same read — RB presses until the front-side crease declares.",
            "kill_look": "8-man box with LBs stacked on the line — check to a quick pass.",
            "vulnerabilities": ["8_man_box", "A_gap_blitz", "slant_away_from_call"],
            "post_snap_alert": "If MIKE scrapes to the frontside, RB cuts back to the backside A gap.",
            "why": "Solid baseline run; stable box-count answer.",
        },
    ],
    "outside_zone": [
        {
            "name": "Outside Zone Weak",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "run_scheme": "Outside zone weak",
            "blocking": "Full stretch zone rules; RB reads EMLOS to inside cut",
            "vs_man": "Stretch forces backside pursuit — RB can outrun pursuit angles.",
            "vs_zone": "Same; cutback dependent on how defenders flow.",
            "kill_look": "Weakside overhang walked up tight — he will wrong-arm the stretch.",
            "vulnerabilities": ["DE_wrong_arm", "overhang_spill", "backside_pursuit"],
            "post_snap_alert": "If EMLOS squeezes hard, RB bends back to the cutback lane immediately.",
            "why": "Horizontal stress with cutback potential.",
        },
    ],
    "duo": [
        {
            "name": "Duo",
            "personnel": "12",
            "formation": "Singleback Doubles Tight",
            "run_scheme": "Duo downhill run",
            "blocking": "Double teams at point of attack; RB reads MIKE",
            "vs_man": "Double teams at POA will move the line of scrimmage — downhill attack.",
            "vs_zone": "MIKE scrape determines the cut: press playside A until he declares.",
            "kill_look": "MIKE stacked inside with no movement — pure two-gapper; crease may not form.",
            "vulnerabilities": ["stacked_MIKE", "two_gap_nose", "A_gap_double_fill"],
            "post_snap_alert": "RB reads MIKE: if he goes backside, press the playside A gap hard.",
            "why": "Short-yardage downhill answer without needing true pullers.",
        },
    ],
    "power": [
        {
            "name": "Power O",
            "personnel": "21",
            "formation": "I-Right",
            "run_scheme": "Power right",
            "blocking": "Backside guard pull; fullback leads through the play-side hole",
            "vs_man": "Pulling guard and FB lead create defined assignment blocks.",
            "vs_zone": "Forces teams to respect the gap scheme on the backside.",
            "kill_look": "Backside LB crashing hard — he will meet the pulling guard and spill it.",
            "vulnerabilities": ["backside_LB_crash", "DE_spill_technique", "over_shifted_front"],
            "post_snap_alert": "FB reads the end: if DE squeezes, FB logs him and RB bounces outside.",
            "why": "Classic gap scheme; defined entry point in tight-yardage situations.",
        },
    ],
    "draw": [
        {
            "name": "Shotgun Draw",
            "personnel": "11",
            "formation": "Shotgun Trips",
            "run_scheme": "Delayed draw",
            "blocking": "Pass-set sell; interior OL climbs late to second level",
            "vs_man": "Pass rush creates natural lanes as OL climbs off their blocks.",
            "vs_zone": "Zone defenders may read the delay; works best vs. heavy rushers.",
            "kill_look": "Spy linebacker or 3-man rush — he will see the delay and fill the gap.",
            "vulnerabilities": ["spy_linebacker", "3_man_rush", "LB_draw_read"],
            "post_snap_alert": "If DEs are wide-rushing upfield, interior A/B gap opens as OL climbs.",
            "why": "Pressure counter on longer downs.",
        },
    ],
    "fade_iso": [
        {
            "name": "Boundary Fade",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "protection": "5-man quick protection",
            "routes": {
                "X": "Fade",
                "H": "Speed out",
                "Y": "Stick",
                "Z": "Slant",
                "RB": "Check-release",
            },
            "vs_man": "Fade wins on the back shoulder vs. off-coverage CB — trust the matchup.",
            "vs_zone": "Limited; CB will drive downhill on the fade break.",
            "kill_look": "CB is pressing — fade is 50/50 at best; consider slant-flat instead.",
            "vulnerabilities": ["press_coverage", "cover_2_corner", "inside_leverage"],
            "post_snap_alert": "If CB gives a hard outside release, throw back-shoulder fade immediately.",
            "why": "Red-zone option when you trust the matchup outside.",
            "td_pct": 0.31,
        },
    ],
    # ── TWO-POINT CONVERSION SHELF ────────────────────────────────────────────
    "two_point": [
        {
            "name": "Rub / Pick Slant",
            "personnel": "11",
            "formation": "Shotgun Bunch Right",
            "protection": "5-man quick",
            "routes": {
                "X": "Clear fade",
                "H": "Inside rub / pick",
                "Y": "Slant off the rub",
                "Z": "Flat",
                "RB": "Check-release middle",
            },
            "vs_man": "Rub creates a natural pick on the inside slant — primary read.",
            "vs_zone": "Slant finds the void; flat stretches the defense wide.",
            "kill_look": "Zone coverage — rub won't free anyone; work the flat or RB instead.",
            "vulnerabilities": ["zone_coverage", "bracket_bunch", "illegal_pick_call"],
            "post_snap_alert": "If CB follows H on the rub route, Y slant is wide open.",
            "why": "Compressed end zone + man coverage = rub is the highest-percentage 2-pt call.",
        },
        {
            "name": "QB Power / Sneak",
            "personnel": "22",
            "formation": "I-Tight",
            "run_scheme": "QB power or sneak option",
            "blocking": "Double team at the center-guard gap; FB leads if QB keeps",
            "vs_man": "Brute force — assignment blocking in tight space.",
            "vs_zone": "Same — half a yard is all you need.",
            "kill_look": "9-man box fully stacked — unlikely to move the pile; consider a pass.",
            "vulnerabilities": ["9_man_box", "no_crease"],
            "post_snap_alert": "QB reads the center gap: if it closes, keep and bounce off the FB shoulder.",
            "why": "When you need a half-yard — most reliable short-yardage 2-pt option.",
        },
        {
            "name": "Shovel / RPO Bubble",
            "personnel": "11",
            "formation": "Shotgun Trips Left",
            "protection": "Run-pass option — mesh action",
            "routes": {
                "X": "Backside clearout",
                "H": "Bubble screen",
                "Y": "Shovel path / mesh",
                "Z": "Block / stalk",
                "RB": "Inside zone mesh",
            },
            "vs_man": "Bubble wins vs. man if the outside is blocked; shovel beats an aggressive DE.",
            "vs_zone": "Give read — if DE crashes, pull and throw bubble to numbers on the perimeter.",
            "kill_look": "LB walked out over H pre-snap — perimeter numbers are even; stay with the shovel.",
            "vulnerabilities": ["pattern_match_cover_4", "cloud_coverage", "DE_contain"],
            "post_snap_alert": "Read the DE: if he crashes the mesh, pull and throw the bubble immediately.",
            "why": "Puts the defense in conflict — can't stop both the run and the perimeter.",
        },
    ],
}

for _fam, _plays in EXTRA_PLAYS.items():
    PLAY_LIBRARY.setdefault(_fam, [])
    PLAY_LIBRARY[_fam].extend(_plays)

