"""
Additional plays merged into ``PLAY_LIBRARY`` (see ``library.py``).

Each entry includes coaching text plus optional metadata used by ``play_metadata.play_selection_weight``.
"""

from __future__ import annotations

from typing import Any, Dict, List

EXTRA_PLAYS: Dict[str, List[Dict[str, Any]]] = {
    "quick_game": [
        {
            "name": "Snag",
            "personnel": "11",
            "formation": "Shotgun Trips Right",
            "protection": "5-man scat / quick slide",
            "motion": "Z fly motion optional",
            "routes": {
                "X": "Hitch / stop",
                "H": "Snag sit at5",
                "Y": "Corner over snag",
                "Z": "Flat",
                "RB": "Swing replace",
            },
            "vs_man": "Snag sit wins vs trail; Z flat pulls the nickel.",
            "vs_zone": "Triangle read: flat-curl-hole — find the linebacker conflict.",
            "kill_look": "Hug rush + cloud flat — throw hitch away from rotation.",
            "vulnerabilities": ["cloud_flat", "pattern_match_flat", "hug_rush"],
            "post_snap_alert": "If MIKE carries H vertical, Y corner is late.",
            "why": "Rhythm three-step answer vs zone-heavy nickel; good on 3rd &4–6.",
            "featured_roles": ["H", "Y"],
            "red_zone_fit": 0.55,
            "medium_fit": 0.62,
            "blitz_answer": 0.6,
            "zone_beater": 0.62,
            "clock_safe": 0.54,
        },
        {
            "name": "Mesh",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "protection": "6-man half-slide",
            "motion": "H jet orbit optional",
            "routes": {
                "X": "Dig sit",
                "H": "Under mesh",
                "Y": "Under mesh opposite",
                "Z": "Pivot / settle",
                "RB": "Arrow then check",
            },
            "vs_man": "Natural rub on mesh; pivot vs man is a chain mover.",
            "vs_zone": "Settle in voids; don't run through linebackers.",
            "kill_look": "Banjo / pattern-match linebackers — work Z pivot late.",
            "vulnerabilities": ["pattern_match", "banjo", "wall_replace"],
            "post_snap_alert": "If linebackers carry vertical, mesh sits pop open.",
            "why": "Man-zone dual read; two-minute and must-convert friendly.",
            "featured_roles": ["H", "Y"],
            "man_beater": 0.58,
            "zone_beater": 0.54,
            "medium_fit": 0.6,
            "blitz_answer": 0.52,
            "clock_safe": 0.5,
        },
        {
            "name": "Double-Slant RPO Look",
            "personnel": "11",
            "formation": "Shotgun Trips Open",
            "protection": "Slant side5-man; peek flat conflict",
            "routes": {
                "X": "Inside slant",
                "H": "Inside slant",
                "Y": "Flat control",
                "Z": "Go clear",
                "RB": "Wide path flat conflict",
            },
            "vs_man": "Slants win immediately; pick rules apply vs tight man.",
            "vs_zone": "Flat holds curl-flat defender; slants into windows.",
            "kill_look": "Press bail with inside help — work flat or backside.",
            "vulnerabilities": ["press_bail", "inside_help", "robber"],
            "post_snap_alert": "If flat defender flies, slant window widens.",
            "why": "Fast pressure answer with defined grass rules.",
            "featured_roles": ["X", "H"],
            "blitz_answer": 0.66,
            "man_beater": 0.6,
            "short_yardage_fit": 0.52,
            "medium_fit": 0.56,
        },
    ],
    "dropback_pass": [
        {
            "name": "Mills",
            "personnel": "11",
            "formation": "Shotgun Trips Right",
            "protection": "6-man slide",
            "routes": {
                "X": "Post",
                "H": "Dig",
                "Y": "Flat",
                "Z": "Clear go",
                "RB": "Check-release",
            },
            "vs_man": "Post beats one-high; dig is the rhythm vs two-high man.",
            "vs_zone": "High-low the safety; dig vs Tampa robber.",
            "kill_look": "Robber MIKE — dig is dangerous; flat may be the answer.",
            "vulnerabilities": ["robber", "tampa_2", "pattern_match"],
            "post_snap_alert": "If safety jumps post, dig wins inside.",
            "why": "Intermediate shot that stresses single-high and MOF closed.",
            "featured_roles": ["H", "X"],
            "explosive_potential": 0.62,
            "medium_fit": 0.64,
            "long_fit": 0.55,
            "zone_beater": 0.58,
            "man_beater": 0.56,
            "risk_level": 0.52,
        },
        {
            "name": "Smash",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "protection": "6-man",
            "routes": {
                "X": "Hitch10–12",
                "H": "Corner12–14",
                "Y": "Flat",
                "Z": "Hitch",
                "RB": "Check-release",
            },
            "vs_man": "Corner beats outside leverage; hitch is the hole shot.",
            "vs_zone": "Classic high-low on the corner; hitch vs squat.",
            "kill_look": "Hard squat corner — hitch may be muddy; work backside.",
            "vulnerabilities": ["squat_corner", "pattern_match_flat"],
            "post_snap_alert": "If corner bails, hitch is immediate.",
            "why": "Zone beater from +12 to +35; keeps offense on schedule.",
            "featured_roles": ["H", "X"],
            "zone_beater": 0.66,
            "medium_fit": 0.66,
            "long_fit": 0.48,
            "clock_safe": 0.44,
        },
        {
            "name": "Flood Sail",
            "personnel": "12",
            "formation": "Shotgun Ace Slot",
            "protection": "7-man",
            "routes": {
                "X": "Flat",
                "Y": "Deep out / sail",
                "H": "Over intermediate",
                "Z": "Backside dig",
                "RB": "Check-release",
            },
            "vs_man": "Sail wins vs one-on-one outside; flat clears space.",
            "vs_zone": "Three-level flood stresses curl-flat defender.",
            "kill_look": "Quarters match — sail may be capped; work dig backside.",
            "vulnerabilities": ["quarters_match", "pattern_match"],
            "post_snap_alert": "If flat defender carries vertical, flat is hot.",
            "why": "Boundary shot vs single-high; two-minute boundary throw.",
            "featured_roles": ["Y"],
            "explosive_potential": 0.58,
            "long_fit": 0.56,
            "medium_fit": 0.58,
            "man_beater": 0.54,
        },
    ],
    "screen": [
        {
            "name": "Jailbreak Screen",
            "personnel": "11",
            "formation": "Shotgun Trips",
            "protection": "Aggressive sell verticals; OL release",
            "routes": {
                "X": "Clear",
                "H": "Clear",
                "Y": "Clear",
                "Z": "Clear",
                "RB": "Jailbreak screen path",
            },
            "vs_man": "Vertical push clears man; RB slips under.",
            "vs_zone": "Best vs aggressive rush — linebackers out of screen lane.",
            "kill_look": "Spy or slow rush — lane may not develop.",
            "vulnerabilities": ["spy_lb", "slow_rush", "screen_read"],
            "post_snap_alert": "Count rushers — need full vertical sell.",
            "why": "Explosive pressure answer when DL races upfield.",
            "featured_roles": ["RB"],
            "blitz_answer": 0.72,
            "explosive_potential": 0.58,
            "long_fit": 0.55,
            "risk_level": 0.48,
        },
        {
            "name": "TE Slip Screen",
            "personnel": "12",
            "formation": "Shotgun Doubles TE",
            "protection": "Quick flash sell; OL screen side release",
            "routes": {
                "X": "Clear out",
                "Y": "TE slip screen",
                "H": "Pick stem",
                "Z": "Clear",
                "RB": "Fake chip",
            },
            "vs_man": "TE slips under man chase; pick stem helps timing.",
            "vs_zone": "Find grass behind DE if flat defender runs.",
            "kill_look": "Flat defender hugging TE — muddy.",
            "vulnerabilities": ["flat_hug", "underneath_read"],
            "post_snap_alert": "If DE two-gaps, throw away from him.",
            "why": "Change-up vs teams keying RB screens.",
            "featured_roles": ["Y"],
            "blitz_answer": 0.6,
            "medium_fit": 0.52,
            "zone_beater": 0.5,
        },
    ],
    "play_action": [
        {
            "name": "Naked Boot Weak",
            "personnel": "12",
            "formation": "Pistol / Singleback",
            "protection": "Naked — TE chip-to-release",
            "routes": {
                "X": "Deep cross",
                "Y": "Flat in boot",
                "H": "Over",
                "Z": "Backside post",
                "RB": "Swing late",
            },
            "vs_man": "Flat in boot is the rhythm; cross vs aggressive safety.",
            "vs_zone": "Boot changes launch; high-low flat defender.",
            "kill_look": "Edge defender unblocked — QB must win with timing.",
            "vulnerabilities": ["edge_unblocked", "contain_rush"],
            "post_snap_alert": "If end crashes, flat is now; if he contains, cross.",
            "why": "Shot answer when linebackers bite hard on run action.",
            "featured_roles": ["Y", "X"],
            "explosive_potential": 0.62,
            "man_beater": 0.56,
            "medium_fit": 0.54,
            "long_fit": 0.5,
            "risk_level": 0.58,
        },
        {
            "name": "Counter PA Deep Over",
            "personnel": "11",
            "formation": "Singleback Twins",
            "protection": "Play-action seven-step timing",
            "routes": {
                "X": "Post",
                "H": "Deep over",
                "Y": "Under",
                "Z": "Comeback",
                "RB": "Check-release",
            },
            "vs_man": "Deep over vs one-high; post clears safety.",
            "vs_zone": "Over settles in hole; post occupies safety.",
            "kill_look": "Four rush with two-high — may need checkdown.",
            "vulnerabilities": ["two_high", "four_rush_safe"],
            "post_snap_alert": "If safety jumps post, over is one-on-one.",
            "why": "Explosive counter off gap run action.",
            "featured_roles": ["H"],
            "explosive_potential": 0.66,
            "long_fit": 0.58,
            "medium_fit": 0.56,
        },
    ],
    "inside_zone": [
        {
            "name": "Inside Zone Weak Bash",
            "personnel": "12",
            "formation": "Shotgun Doubles Tight",
            "run_scheme": "Inside zone weak with TE surface",
            "blocking": "Covered/uncovered; TE helps seal C-gap entry",
            "vs_man": "Numbers to weak; bash tag can flip if MIKE overplays.",
            "vs_zone": "Press weak A-gap; cutback vs overflow.",
            "kill_look": "Heavy weak walk-down — check quick game.",
            "vulnerabilities": ["weak_walk_down", "spill_edge"],
            "post_snap_alert": "If 3-tech penetrates weak, cutback strong.",
            "why": "Short-yardage and goal-line viable without pulling.",
            "featured_roles": ["RB"],
            "short_yardage_fit": 0.68,
            "red_zone_fit": 0.6,
            "goal_line_fit": 0.62,
            "fourth_down_fit": 0.55,
        },
        {
            "name": "Split Zone",
            "personnel": "11",
            "formation": "Shotgun Trips",
            "run_scheme": "Split flow zone — H arc or slice",
            "blocking": "H arcs to force; OL zone away from slice",
            "vs_man": "Arc creates extra gap; good vs aggressive edges.",
            "vs_zone": "Slice holds backside linebacker.",
            "kill_look": "Spill-and-overlap — bounce may be dead.",
            "vulnerabilities": ["spill", "overlap"],
            "post_snap_alert": "If arc gets grabbed, bend to cutback.",
            "why": "Change-up vs teams that squeeze inside zone.",
            "featured_roles": ["RB", "H"],
            "medium_fit": 0.58,
            "long_fit": 0.46,
            "backed_up_fit": 0.52,
        },
    ],
    "outside_zone": [
        {
            "name": "Wide Zone Strong",
            "personnel": "12",
            "formation": "Shotgun Ace",
            "run_scheme": "Wide zone strong — TE surface",
            "blocking": "Reach series; RB tracks TE hip",
            "vs_man": "Stretch forces secondary to fit fast.",
            "vs_zone": "Cutback vs overpursuit.",
            "kill_look": "Wide 9 spill — bounce muddy.",
            "vulnerabilities": ["wide_9", "spill"],
            "post_snap_alert": "If EMLOS flies, tight bend downhill.",
            "why": "Field-stretcher that pairs with boot and quick game.",
            "featured_roles": ["RB"],
            "medium_fit": 0.6,
            "clock_safe": 0.58,
        },
    ],
    "duo": [
        {
            "name": "Duo Tight Surface",
            "personnel": "13",
            "formation": "Goal Line / Heavy Ace",
            "run_scheme": "Duo with TE wing",
            "blocking": "Double teams; RB reads MIKE",
            "vs_man": "Extra gap with wing — movement at LOS.",
            "vs_zone": "Vertical displacement on DL.",
            "kill_look": "Penetrating shade — may need bounce.",
            "vulnerabilities": ["shade_penetration"],
            "post_snap_alert": "Press A-gap until MIKE declares.",
            "why": "Goal-line and3rd/4th & 1 answer.",
            "featured_roles": ["RB"],
            "short_yardage_fit": 0.82,
            "goal_line_fit": 0.85,
            "fourth_down_fit": 0.72,
            "red_zone_fit": 0.72,
        },
    ],
    "power": [
        {
            "name": "Down G",
            "personnel": "22",
            "formation": "I-Right Tight",
            "run_scheme": "Down G pull to TE side",
            "blocking": "Kick-out and wrap; downhill track",
            "vs_man": "Gap scheme wins in tight spaces.",
            "vs_zone": "Forces linebackers to fit downhill.",
            "kill_look": "Edge spill — bounce read for RB.",
            "vulnerabilities": ["spill", "penetration"],
            "post_snap_alert": "FB reads force player; RB tracks inside leg.",
            "why": "Classic short-yardage and GL complement to Power O.",
            "featured_roles": ["RB"],
            "short_yardage_fit": 0.84,
            "goal_line_fit": 0.86,
            "fourth_down_fit": 0.7,
        },
    ],
    "draw": [
        {
            "name": "Draw vs Wide-9",
            "personnel": "11",
            "formation": "Shotgun Empty / Dbl",
            "run_scheme": "Draw with tackle show pass set",
            "blocking": "Vertical pass set; late climb",
            "vs_man": "Rush lanes create natural creases.",
            "vs_zone": "Works when linebackers retreat.",
            "kill_look": "Draw read linebackers — late insert kills lane.",
            "vulnerabilities": ["draw_read", "spy"],
            "post_snap_alert": "If tackles overset, A-gap pops.",
            "why": "Long-yardage and two-minute neutralizer vs speed rush.",
            "featured_roles": ["RB"],
            "blitz_answer": 0.64,
            "long_fit": 0.62,
            "medium_fit": 0.54,
        },
    ],
    "fade_iso": [
        {
            "name": "Slot Fade / Pylon",
            "personnel": "11",
            "formation": "Shotgun Trips",
            "protection": "5-man quick",
            "routes": {
                "X": "Slant",
                "H": "Fade / pylon",
                "Y": "Flat",
                "Z": "Clear",
                "RB": "Check-release",
            },
            "vs_man": "Slot fade vs nickel — leverage to pylon.",
            "vs_zone": "Flat holds flat defender; fade vs squat.",
            "kill_look": "Bracket slot — work slant away.",
            "vulnerabilities": ["bracket", "pattern_match"],
            "post_snap_alert": "If nickel is inside shade, fade wins outside.",
            "why": "Red-zone specialty when boundary is capped.",
            "featured_roles": ["H"],
            "red_zone_fit": 0.78,
            "goal_line_fit": 0.72,
            "man_beater": 0.6,
            "explosive_potential": 0.52,
        },
        {
            "name": "Mesh Pivot RZ",
            "personnel": "11",
            "formation": "Shotgun Bunch",
            "protection": "Quick5-man",
            "routes": {
                "X": "Pivot",
                "H": "Rub mesh",
                "Y": "Flat",
                "Z": "Corner",
                "RB": "Check",
            },
            "vs_man": "Rub/pick rules create separation in tight space.",
            "vs_zone": "Pivot sits; corner occupies safety.",
            "kill_look": "Zone match — pivot may be capped.",
            "vulnerabilities": ["pattern_match"],
            "post_snap_alert": "Throw pivot vs inside leverage.",
            "why": "Man-zone red-zone answer when fade is bracketed.",
            "featured_roles": ["H", "X"],
            "red_zone_fit": 0.8,
            "man_beater": 0.62,
            "zone_beater": 0.55,
        },
    ],
    "two_point": [
        {
            "name": "Fade-Stop Back Shoulder",
            "personnel": "11",
            "formation": "Shotgun Doubles",
            "protection": "Quick 5-man",
            "routes": {
                "X": "Back-shoulder fade-stop",
                "H": "Slant",
                "Y": "Flat",
                "Z": "Clear",
                "RB": "Check",
            },
            "vs_man": "Back shoulder gives QB a defined window.",
            "vs_zone": "Slant may be the answer vs inside zones.",
            "kill_look": "Press with help inside — fade is tight.",
            "vulnerabilities": ["press_help", "bracket"],
            "post_snap_alert": "If CB is soft, throw fade-stop early.",
            "why": "2-pt specialty when rub isn't legal or vs zone.",
            "featured_roles": ["X"],
            "red_zone_fit": 0.88,
            "man_beater": 0.64,
            "risk_level": 0.48,
        },
    ],
}
