"""Baseline revision — no domain tables yet.

Domain ORM models and autogenerated revisions will follow. This revision
exists so ``alembic upgrade head`` succeeds and ``alembic_version`` is created.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-04-18

"""

from __future__ import annotations

from typing import Sequence, Union

revision: str = "0001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ORM tables will be introduced in a later revision.
    pass


def downgrade() -> None:
    pass
